version: '3.8'

services:
  php:
    build:
      context: .
    image: s:
  nginxphpf-docker/php:dev
    restart: on-failure
    enviroment:
      APP_ENV: dev
      APP_DEBUG: 1
      PHP_DATE_ZONE: ${PHP_DATE_TIMEZONE:-UTC}

  nginx:
    build:
      context: .
      image: sf-docker/nginx:dev
      restart: on-failure
      depends-on:
        - php
      ports:
        - "8080:80"
